import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'tailwindcss/tailwind.css'
import Header from "@/src/components/overallUse/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <main className='flex flex-col-reverse'>
      <div className="container">
        {children}
      </div>
      <header>
        <Header isAuthorized={true}/>
      </header>
    </main>
    </body>
    </html>
  );
}
